## --------------------------------------------------------------
## |                    compulsory parameters                   #
## --------------------------------------------------------------
camera_name: ""
camera_id: 0 #if the camera_name is not defined, the id is used
#StreamRole documentation: https://libcamera.org/api-html/namespacelibcamera.html#a295d1f5e7828d95c0b0aabc0a8baac03
stream_role: "still" # [raw, still, video, viewfinder]
#pixel format documentation: https://libcamera.org/api-html/build_2include_2libcamera_2formats_8h_source.html
pixel_format: "RGB888"
resolution:
  width: 1456
  height: 1088

#frame_id and calib_url parameters are set using launch file

## --------------------------------------------------------------
## |                     optional parameters                    #
## --------------------------------------------------------------
# documentation: https://libcamera.org/api-html/namespacelibcamera_1_1controls.html
control:
  exposure_time: 100
  exposure_value: -8.0
  brightness: -1.0
  sharpness: 0.0
  colour_gain: 0.0
  saturation: 0.0
  contrast: 0.0
  awb_enable: false
  awb_mode: 0
  hdr_mode: 0
  analogue_gain: 1.0
  scaler_crop: "(0, 0)/32x32"
  ae_enabled: false
  ae_exposure_mode: 0
  ae_flicker_mode: 0
  ae_flicker_period: 100
  ae_constraint_mode: 0
  ae_metering_mode: 0
  stats_output_enable: false 
  noise_reduction_mode: 0
  frame_duration_limits: 16562
